USE LampStoreDB;
GO

SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET NUMERIC_ROUNDABORT OFF;
GO

DELETE FROM ProductTags;
DELETE FROM ProductVariants;
DELETE FROM ProductImages;
DELETE FROM ProductReviews;
DELETE FROM Products;
DELETE FROM Tags;
DELETE FROM Categories;
PRINT N'All cleaned';
GO
